# Generated by Django 4.2.1 on 2023-07-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cidade',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
